parser: '@typescript-eslint/parser'
env:
  node: true
  browser: true
plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'import-path'
  - 'import'
globals:
  Playwright: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parserOptions:
  ecmaVersion: 8
  requireConfigFile: false

overrides:
  - files:
      - '**/*.ts'
    extends:
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@typescript-eslint/eslint-recommended'
    rules:
      '@typescript-eslint/no-explicit-any': 'off'
      '@typescript-eslint/ban-ts-ignore': 'off'
      '@typescript-eslint/ban-ts-comment': 'off'
      'prettier/prettier': ['error']
      'prefer-const': ['error', { 'destructuring': 'all', 'ignoreReadBeforeAssign': false }]
      '@typescript-eslint/no-unused-vars': 'off'
      'no-duplicate-imports': 'error'
      'import/no-duplicates': 'error'
      'import-path/parent-depth': ['error', 1]
      prefer-spread: 'off'
